---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.7
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[cic_trendmicro_agent::default]
      - recipe[cic_trendmicro_agent::cron-dsa-check-in-with-manager]
      - recipe[cic_trendmicro_agent::cron-dsa-scan-for-malware]
      - recipe[cic_trendmicro_agent::cron-dsa-recommend-scan]
      - recipe[cic_trendmicro_agent::cron-dsa-integrity-scan]
      - recipe[cic_trendmicro_agent::cron-dsa-rebuild-integrity-baseline]
      - recipe[cic_trendmicro_agent::cron-dsa-agent-reset]
      
      
      
    attributes:
