name             'cic_trendmicro_agent'
maintainer       'veena dev'
maintainer_email 'veenavdev@gmail.com'
license          'All rights reserved'
description      'Installs/Configures cic-trendmicro_agent'
long_description 'Installs/Configures cic-trendmicro_agent'
version          '0.1.0'
