name             'cic_trendmicro_agent'
maintainer       'Shubham Dhoka'
maintainer_email 'shubham.dhoka@reancloud.com'
license          'All rights reserved'
description      'Installs/Configures cic-trendmicro'
long_description 'Installs/Configures cic-trendmicro'
version          '0.1.0'
