variable "aws_region" {}
variable "environment" {}
variable "azs" {}
variable "ami_id" {}
variable "instance_type" {}
variable "product_name" {}
variable "owner" {}
variable "my_ip" {}
variable "key_pair_public_key" {}
variable "acct_remote_state_bucket" {}
variable "acct_remote_state_key" {}
variable "network_remote_state_bucket" {}
variable "network_remote_state_key" {}
variable "subnets" {}
variable "xelb_subnets" {}
variable "key_pair_name" {}
